# Generated by Django 5.1.2 on 2024-12-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '菜单角色关联表',
                'db_table': 'menu_roles',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='菜单名称')),
                ('path', models.CharField(max_length=100, null=True, verbose_name='菜单路径')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='图标')),
            ],
            options={
                'verbose_name': '菜单',
                'db_table': 'menus',
            },
        ),
    ]
