# Generated by Django 5.1.2 on 2024-12-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, null=True, verbose_name='验证码')),
            ],
            options={
                'verbose_name': '注册',
                'db_table': 'enroll',
            },
        ),
    ]
