# Generated by Django 5.1.2 on 2024-12-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleSnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfiles',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='文件路径'),
        ),
    ]
