# Generated by Django 5.1.2 on 2024-12-20 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleSnalysis', '0002_userfiles_url'),
        ('users', '0003_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfiles',
            name='url',
            field=models.CharField(max_length=100, null=True, verbose_name='访问路径'),
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ramnit', models.IntegerField(null=True, verbose_name='Ramnit')),
                ('Lollipop2', models.IntegerField(null=True, verbose_name='Lollipop2')),
                ('Kelihos_ver3', models.IntegerField(null=True, verbose_name='Kelihos_ver3')),
                ('Vundo', models.IntegerField(null=True, verbose_name='Vundo')),
                ('Simda', models.IntegerField(null=True, verbose_name='Simda')),
                ('Tracur', models.IntegerField(null=True, verbose_name='Tracur')),
                ('Kelihos_ver1', models.IntegerField(null=True, verbose_name='Kelihos_ver1')),
                ('Obfuscator_ACY', models.IntegerField(null=True, verbose_name='Obfuscator_ACY')),
                ('Gatak', models.IntegerField(null=True, verbose_name='Gatak')),
                ('UserFile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleSnalysis.userfiles', verbose_name='文件')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户模型',
                'db_table': 'UserModel',
            },
        ),
        migrations.CreateModel(
            name='UserModelDataId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, null=True, verbose_name='id')),
                ('usermodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleSnalysis.usermodel', verbose_name='用户模型')),
            ],
            options={
                'verbose_name': '用户模型数据id',
                'db_table': 'UserModelDataId',
            },
        ),
        migrations.CreateModel(
            name='UserModelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ramnit', models.IntegerField(null=True, verbose_name='Ramnit')),
                ('Lollipop2', models.IntegerField(null=True, verbose_name='Lollipop2')),
                ('Kelihos_ver3', models.IntegerField(null=True, verbose_name='Kelihos_ver3')),
                ('Vundo', models.IntegerField(null=True, verbose_name='Vundo')),
                ('Simda', models.IntegerField(null=True, verbose_name='Simda')),
                ('Tracur', models.IntegerField(null=True, verbose_name='Tracur')),
                ('Kelihos_ver1', models.IntegerField(null=True, verbose_name='Kelihos_ver1')),
                ('Obfuscator_ACY', models.IntegerField(null=True, verbose_name='Obfuscator_ACY')),
                ('Gatak', models.IntegerField(null=True, verbose_name='Gatak')),
                ('usermodeldataid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleSnalysis.usermodeldataid', verbose_name='用户模型数据id')),
            ],
            options={
                'verbose_name': '用户模型数据结果',
                'db_table': 'UserModelResult',
            },
        ),
    ]
